"""
AutoSys System Agent wire protocol — newline-delimited JSON over TCP.

In real AutoSys the Scheduler ACE communicates with System Agents over TCP
port 7520 using a proprietary binary format.  We replace that with a simple
newline-delimited JSON ("NDJSON") protocol that is trivially inspectable with
``nc`` or ``telnet`` — making it far more educational.

Protocol mechanics
------------------
Each conversation is a single request → single response exchange over a
short-lived TCP connection:

    client  →  {"type": "heartbeat"}\n
    server  →  {"type": "alive", "machine_name": "etl-server-01"}\n
    (connection closed)

Message types
-------------
heartbeat         →  alive
status            →  status
dispatch          →  accepted | rejected
kill              →  killed
get_output        →  output

Wire format
-----------
Each message is a UTF-8-encoded JSON object on a single line (no embedded
newlines).  The terminating ``\\n`` is the frame delimiter — the same format
used by NDJSON, JSON-RPC over streams, and most modern line-oriented
protocols.

Usage
-----
    # Sender (scheduler side)
    from autosys.agent.protocol import send_message
    resp = send_message("etl-server-01", 7520, HeartbeatRequest())
    assert resp["type"] == "alive"

    # Receiver (agent side)
    from autosys.agent.protocol import decode_message
    msg = decode_message(line_bytes)
    if msg["type"] == "dispatch":
        ...
"""

from __future__ import annotations

import json
import socket
from typing import Any, Optional

from pydantic import BaseModel


# ===========================================================================
# Request / Response models
# ===========================================================================

class HeartbeatRequest(BaseModel):
    """
    Ping the agent to verify it is alive.

    Sent by the Scheduler ACE when a ``CHECK_HEARTBEAT`` event is processed.
    The agent responds with ``HeartbeatResponse``.  If no response arrives
    within the timeout, the Scheduler marks the machine as DOWN and raises
    an alarm.
    """
    type: str = "heartbeat"


class HeartbeatResponse(BaseModel):
    """Agent → Scheduler: I am alive."""
    type:         str = "alive"
    machine_name: str


class StatusRequest(BaseModel):
    """
    Request a summary of the agent's current state.

    Used by ``autosys machine check <name>`` to show active jobs, uptime,
    and PID count without modifying any state.
    """
    type: str = "status"


class StatusResponse(BaseModel):
    """Agent → Scheduler: current state snapshot."""
    type:         str = "status"
    machine_name: str
    host:         str
    port:         int
    active_jobs:  list[str]
    uptime_secs:  float
    pid:          Optional[int] = None


class DispatchRequest(BaseModel):
    """
    Ask the agent to execute a job command.

    Sent by the Scheduler ACE when a CMD job is dispatched to a remote
    machine.  The agent forks the process, updates the DB, and responds
    immediately with ``DispatchResponse`` (the agent does NOT wait for the
    job to finish before responding).

    Parameters
    ----------
    run_id:
        UUID generated by the Scheduler for this execution attempt.
        Written to ``job_runs.run_id`` so output and history queries
        can use it as a join key.
    job_name:
        Used for log messages and DB lookups.
    command:
        Already ``%%VAR%%``-expanded command string (expansion happens on
        the Scheduler side because the Scheduler owns the globals table).
    max_run_secs:
        If set, the agent kills the process after this many seconds
        (from ``max_run_alarm × 60`` in the JIL definition).
    """
    type:            str   = "dispatch"
    run_id:          str
    job_name:        str
    command:         str
    max_run_secs:    Optional[float] = None
    max_exit_success: Optional[int]  = None   # None → only exit 0 = SUCCESS


class DispatchResponse(BaseModel):
    """Agent → Scheduler: job accepted and process started."""
    type:    str = "accepted"
    run_id:  str
    message: str = ""


class DispatchRejected(BaseModel):
    """Agent → Scheduler: could not start the job."""
    type:   str = "rejected"
    run_id: str
    reason: str


class KillRequest(BaseModel):
    """
    Ask the agent to terminate a running job.

    Corresponds to the KILLJOB event.  The Scheduler sends this after
    setting the job's status to TERMINATED in the DB; the agent then
    sends SIGTERM (→ SIGKILL after grace period) to the OS process.
    """
    type:     str = "kill"
    job_name: str


class KillResponse(BaseModel):
    """Agent → Scheduler: kill signal sent (or process not found)."""
    type:     str = "killed"
    job_name: str
    found:    bool


class GetOutputRequest(BaseModel):
    """
    Request captured output lines for a run.

    The scheduler uses this for ``autosys jobs tail`` on output that was
    stored by a remote agent.  Typically the agent writes output directly
    to the shared DB, so this request is only needed when the DB is not
    shared (Phase 7+ with PostgreSQL or separate SQLite files per agent).
    """
    type:      str = "get_output"
    run_id:    str
    from_line: int = 0


class GetOutputResponse(BaseModel):
    """Agent → Scheduler: output lines from a single run."""
    type:  str = "output"
    run_id: str
    lines: list[dict]   # [{"line_no": 1, "stream": "stdout", "content": "..."}]


# ===========================================================================
# Wire encoding / decoding
# ===========================================================================

def encode_message(msg: BaseModel) -> bytes:
    """Serialize a message to wire bytes (UTF-8 JSON + newline)."""
    return (msg.model_dump_json() + "\n").encode("utf-8")


def encode_dict(d: dict) -> bytes:
    """Serialize a plain dict (for error responses built without a model)."""
    return (json.dumps(d) + "\n").encode("utf-8")


def decode_message(line: bytes) -> dict[str, Any]:
    """
    Deserialize one wire line to a plain dict.

    Returns an empty dict with ``type = "parse_error"`` if the line is
    not valid JSON — the agent logs it and continues serving.
    """
    try:
        return json.loads(line.decode("utf-8").strip())
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        return {"type": "parse_error", "error": str(exc)}


# ===========================================================================
# Synchronous socket send/receive  (scheduler → agent)
# ===========================================================================

def send_message(
    host:    str,
    port:    int,
    message: BaseModel,
    timeout: float = 10.0,
) -> dict[str, Any]:
    """
    Send *message* to an agent server and return the parsed response.

    This is a synchronous blocking call — suitable for use in the event
    processor tick (which is sync) without asyncio complications.

    Parameters
    ----------
    host, port:
        Agent server address.
    message:
        Any Pydantic model from this module (e.g. ``HeartbeatRequest()``).
    timeout:
        Socket timeout in seconds.

    Returns
    -------
    dict
        The decoded response dict, or ``{"type": "error", "reason": ...}``
        on connection failure.

    Raises
    ------
    Does NOT raise — connection errors are returned as error dicts so the
    caller can decide whether to log, alarm, or retry.
    """
    try:
        with socket.create_connection((host, port), timeout=timeout) as sock:
            sock.sendall(encode_message(message))
            # Read until newline (response is always one line)
            buf = b""
            while b"\n" not in buf:
                chunk = sock.recv(4096)
                if not chunk:
                    break
                buf += chunk
            return decode_message(buf)
    except OSError as exc:
        return {"type": "error", "reason": str(exc)}
